name: build_tag

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_package:
    runs-on: ["ubuntu-latest"]
    strategy:
      matrix:
        network: ["test", "prod"]
    steps:
      - name: Show ref
        run: |
          echo "Ref is ${{ github.ref_name }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
          
      - name: Build rust and package
        env:
          NETWORK: ${{ matrix.network }}.mobilecoin.com
          SGX_MODE: HW
          IAS_MODE: PROD
        run: |
          ./build_rust.sh
          ./make_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.network }}-package"
          path: package_*.tar.gz
          if-no-files-found: error
          compression-level: 0

